### ISSUE TITLE
NoSuchMethodError using Gradle 6.2.1

### ISSUE THREAD

**Issue by paulk-asert** [blindpirate/gradle-legacy-osgi-plugin#2]
```
java.lang.NoSuchMethodError: 'void org.gradle.util.SingleMessageLogger.nagUserOfPluginReplacedWithExternalOne(java.lang.String, java.lang.String)'
        at com.github.blindpirate.osgi.plugins.osgi.OsgiPlugin.apply(OsgiPlugin.java:42)
        at com.github.blindpirate.osgi.plugins.osgi.OsgiPlugin.apply(OsgiPlugin.java:37)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
        ...
```

**Comment by blindpirate** [comment]
@paulk-asert How to reproduce it?

**Comment by paulk-asert** [comment]
I just upgraded gradle version on groovy codebase and tried `gradle tasks`.

**Comment by blindpirate** [comment]
OK. Will try to fix it today.

**Comment by paulk-asert** [comment]
It is not super urgent but a fix when you get a chance would be great! :-)

**Comment by paulk-asert** [comment]
Works and your Groovy PR is merged. Thanks.
